import Link from "next/link";
import { LegalShell } from "../_components/legal-shell";
import { detailMetadata } from "@/lib/metadata";
import { currentLaunch } from "@/lib/launch-stage";
import { MARKETPLACE_PLATFORM_FEE_PERCENT } from "@/lib/plans";
import { MarketplaceCatalog } from "../_components/marketplace-catalog";

export const metadata = detailMetadata("Creator marketplace", "Free and paid Spark Plug profiles, themes, motion packs, and rights-cleared LoRA adapters.", "/marketplace");

export default function MarketplacePage() {
  return <LegalShell eyebrow={`${currentLaunch.stage.toUpperCase()} / CREATOR MARKETPLACE`} title="Share the setup. Sell the craft—not control of the machine." summary="Everyone can browse and install approved free releases. Planned Pro accounts may publish free or paid profiles, themes, motion packs, and rights-cleared LoRA adapters after review.">
    <h2>Commercial preview</h2><p>The cards on the homepage are examples. Accounts, publishing, sales, subscriptions, seller onboarding, and payouts are not active yet. <Link href="/pricing">Review the planned Community and Pro boundary</Link>.</p>
    {currentLaunch.marketplaceSales ? <MarketplaceCatalog /> : null}
    <h2>Profiles are configuration—not plug-ins</h2><p>Submissions must be declarative, schema validated, revision pinned, checksummed, licensed, provenance labeled, and reviewed. They cannot contain scripts, credentials, secrets, host paths, commands, or private output references.</p>
    <h2>Open in Spark Plug</h2><ol><li>A creator exports a scrubbed profile from Spark Plug or builds one with the planned Pro website editor.</li><li>The marketplace validates, versions, signs, and reviews the profile document.</li><li>After a free download or purchase, the document opens in Spark Plug and displays every imported setting before approval.</li><li>GW Broker checks the user&rsquo;s engines and local model inventory. Missing models receive a clear acquisition plan with their source, pinned revision, files, license, size, memory fit, and checksum.</li><li>The user approves any model download and edits or saves the profile. Import never starts a model or job automatically.</li></ol>
    <h2>Free and paid listings</h2><p>A Pro creator may choose $0.00 or an approved one-time price for each listing. GameWorlds&rsquo; platform fee is <strong>{MARKETPLACE_PLATFORM_FEE_PERCENT}% of each paid sale</strong>. Stripe processing, Connect, tax, refund, dispute, and currency costs are separate and must be shown before seller activation. Stripe Connect will handle identity and payout onboarding.</p>
    <h2>Compatibility is part of the listing</h2><p>Creators must publish every configuration they actually tested: computer maker and model, operating system, CPU architecture, system memory, GPU and VRAM when applicable, engine and version, exact model revision, and test date. A buyer can compare that evidence with the local preflight report before installing. “Works everywhere” is not an acceptable claim.</p>
    <h2>Creator support first, GameWorlds escalation second</h2><p>The creator owns first-line questions, troubleshooting, and revisions for their listing. The marketplace keeps the listing version, conversation, compatibility evidence, and cure history together. A buyer may escalate an unresolved case to GameWorlds administrators for independent reproduction, moderation, or refund review.</p>
    <h2>Refund boundary</h2><p>A hardware mismatch outside the creator&rsquo;s declared compatibility is not, by itself, a product defect. A refund may be approved when mandatory law requires it, when GameWorlds reproduces a defect on a declared supported configuration and the creator cannot fix it after a reasonable cure opportunity, or when the creator abandons the listing or case. Read the <Link href="/legal/refunds">Marketplace Support &amp; Refund Policy</Link>.</p>
    <h2>Models, adapters, and licenses</h2><p>A profile may reference compatible models without reselling their weights. A LoRA adapter may be distributed only when the creator has rights to its training data, base-model use, output, artwork, and commercial distribution. Every listing identifies what is included and what the buyer must obtain separately.</p>
    <h2>Low-call design</h2><p>The local app does not continuously phone home. Catalog metadata uses cache and update deltas; Pro status uses a short signed snapshot stored locally; Stripe webhooks update billing state; and paid packages use short-lived download grants. Network calls happen when a user signs in, browses, buys, downloads, publishes, views creator analytics, or explicitly refreshes near entitlement expiry.</p>
    <h2>Website authority, app convenience</h2><p>The website owns storefronts, publishing, checkout, support cases, refunds, and moderation. The Spark Plug app may show the same catalog from a read-only CDN snapshot cached for at least one hour. Local page changes and AI work never query the marketplace. A network request occurs only when the hourly catalog is explicitly refreshed, a package is downloaded, or a signed-in user chooses a hosted commerce action.</p>
    <h2>Hugging Face license gate</h2><p>Marketplace profiles reference pinned Hugging Face repositories; they do not bundle or resell model weights. A paid profile cannot publish until GameWorlds has recorded an exact repository, revision, and license decision that permits a paid configuration reference. Unknown, expired, noncommercial, or blocked decisions fail closed. Restricted or unusually permissive “uncensored” models require prominent safety labels and may be blocked by moderation.</p>
    <h2>Themes and motion</h2><p><Link href="/themes">Explore the Themes page</Link> for the bundled $0.00 collection and future Pro presentation packs.</p>
    <h2>Review, reporting, and takedowns</h2><p>Publication remains moderated. Checksums, risk labels, review notes, version history, reports, removals, appeals, refunds, and takedowns stay auditable. Payment or creator verification never bypasses technical validation.</p>
  </LegalShell>;
}
